image: java:openjdk-8-jre

before_script:
    - apt-get install gradle
  
testing:
    script:
        - gradle :core:test

javadocs:
    script:
        - javadoc -d ./docs -sourcepath ./core/src -subpackages com
