image: java:openjdk-8-jdk

before_script:
    - apt-get update && apt-get install -y gradle
  
testing:
    script:
        - gradle :core:test

javadocs:
    script:
        - javadoc -d ./docs -sourcepath ./core/src -subpackages com
