image: java:openjdk-8-jdk

before_script:
    - apt-get update && apt-get install -y gradle
  
all_tasks:
    script:
        - gradle :core:test
        - javadoc -d ./docs -sourcepath ./core/src -subpackages com
        - git config --global user.name 'Conductor Gitlab CI Runner'
        - git config --global user.email 'gitlab.runner@conductor.com'
        - git remote --set-url origin https://gitlab.com/rubberydub/conductor.git
        - git add .
        - git commit -m 'tests passed, Javadocs generated'
        - git push origin production
